gui:
  theme:
    lightTheme: false
    activeBorderColor:
      - white
      - bold
    inactiveBorderColor:
      - black
      - bold
    optionsTextColor:
      - blue
    selectedLineBgColor:
      - default
    selectedRangeBgColor:
      - blue
git:
  paging:
    colorArg: always
    pager: delta --dark --paging=never --24-bit-color=never
