#!/usr/bin/env bash
# vim: ft=sh

# I have this symlinked to /usr/local/bin/jdtls

# NOTE:
# This doesn't work as is on Windows. You'll need to create an equivalent `.bat` file instead
#
# NOTE:
# If you're not using Linux you'll need to adjust the `-configuration` option
# to point to the `config_mac' or `config_win` folders depending on your system.

# ADDED
JAVA_HOME="/Library/Java/JavaVirtualMachines/openjdk-11.0.2.jdk/Contents/Home"

JAR="$HOME/.config/jdtls/plugins/org.eclipse.equinox.launcher_*.jar"
# GRADLE_HOME=$HOME/.gradle java \
GRADLE_HOME=$HOME/.gradle /Library/Java/JavaVirtualMachines/openjdk-11.0.2.jdk/Contents/Home/bin/java \
  -javaagent:$HOME/bakdata/dependencies/lombok.jar \
  -Declipse.application=org.eclipse.jdt.ls.core.id1 \
  -Dosgi.bundles.defaultStartLevel=4 \
  -Declipse.product=org.eclipse.jdt.ls.core.product \
  -Dlog.protocol=true \
  -Dlog.level=ALL \
  -Xms1g \
  -Xmx2G \
  -jar $(echo "$JAR") \
  -configuration "$HOME/.config/jdtls/config_mac" \
  -data "${1:-$HOME/bakdata/workspace}" \
  --add-modules=ALL-SYSTEM \
  --add-opens java.base/java.util=ALL-UNNAMED \
  --add-opens java.base/java.lang=ALL-UNNAMED
